### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by vimkaf** [dajoha/lapce-php-intelephense#1]
After installing the plugin, I do not see any effect of the plugin in my project. I have reloaded the plugin several times and no errors are thrown in the lapce output terminal. I am using Kali Linux

**Comment by Hasnayeen** [comment]
you have to install Intelephense npm package for lsp server.
`npm i intelephense -g`
then add the path to intelephense binary in plugin settings of lapce (LSP: Server path)
to find the binary run this command `whereis intelephense`

**Comment by vimkaf** [comment]
I have done all that , still plugin is not working

![image](https://user-images.githubusercontent.com/2923113/209586079-b80e8e98-fbc8-48df-a2db-c9bb26533d25.png)

![image](https://user-images.githubusercontent.com/2923113/209586110-5752dede-91df-404d-b82a-04ec1f1f6a28.png)

**Comment by Hasnayeen** [comment]
@vimkaf should be written like below

```toml
[lapce-php-intelephense]
"lsp.serverPath" = "/home/kay/node-v18.12.1-linux-x64/bin/intelephense"
```
